[profile.default]
src = "src"
out = "out"
fs_permissions = [
    { access = "read", path = "./testdata" },
    { access = "read", path = "./deployed_contracts.json" }
]

solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200

libs = ["dependencies"]

[profile.no-vlayer]
no-match-path = "test/vlayer/*"

[profile.vlayer]
match-path = "test/vlayer/*"

[dependencies]
forge-std = "1.9.4"
"@openzeppelin-contracts" = "5.0.1"
risc0-ethereum = { version = "2.1.1", url = "https://github.com/vlayer-xyz/risc0-ethereum/releases/download/v2.1.1-soldeer/contracts.zip" }

[rpc_endpoints]
ethereum = "https://eth.drpc.org"
optimism = "https://mainnet.optimism.io"
base = "https://mainnet.base.org"
flow-evm-mainnet = "https://mainnet.evm.nodes.onflow.org"

arbitrum-sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
base-sepolia = "https://sepolia.base.org"
optimism-sepolia = "https://sepolia.optimism.io"
sepolia = "https://eth-sepolia.public.blastapi.io"
worldchain-sepolia = "https://worldchain-sepolia.gateway.tenderly.co"
flow-evm-testnet = "https://testnet.evm.nodes.onflow.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[soldeer]
# whether soldeer manages remappings
remappings_generate = false

# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false

# whether to suffix the remapping with the version: `name-a.b.c`
remappings_version = true

# a prefix to add to the remappings ("@" would give `@name`)
remappings_prefix = ""

# where to store the remappings ("txt" for `remappings.txt` or "config" for `foundry.toml`)
# ignored when `soldeer.toml` is used as config (uses `remappings.txt`)
remappings_location = "txt"

# whether to install sub-dependencies or not. If true this wil install the dependencies of dependencies 1 level down.
recursive_deps = true
